title: Alex's Awesome Website
author: Alexander Price
logo: /assets/img/logo.png
description: 2025 Tesla Model 3 Long Range Dual Motor
google_analytics: Test "Google Analytics"
theme: jekyll-theme-modernist
