title: "Alex's Awesome Website"
author: "Alexander Price"
logo: "/assets/img/logo.png"
description: "2025 Tesla Model 3 Long Range Dual Motor"
# google_analytics: "G-XXXXXXXXXX"
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
