title: Alexander's Super Duper Cool and Amazing Website of Doom, Mystery and Magic
author: Alexander Price
email: alexanderprice2@mail.weber.edu
description: >- # this means to ignore newlines until "baseurl:"
  My website is designed to blow your mind. Proceed at your own risk.
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: "jekyll-theme-minimal"
